# Generated by Django 5.2.3 on 2026-03-24 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_order_idempotency_async_fulfillment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
